### ISSUE TITLE
Lux Light material

### ISSUE THREAD

**Issue by patro1** [LuxCoreRender/MaxToLux#31] opened 2021-01-17 21:55 UTC
known issue: when adding lux sky to scene, the background is black
but adding a Lux Light material to a mesh in the scene or enabling emission in the material setting will add automatically lux sky to the scene

**Comment by OmidGhotbi** [comment] 2021-01-19 00:15
The first part about the black sky will be fixed, but the second part is not a bug. There is an option for it called "Auto default light", you can disable it in the light sitting panel inside renderer settings.

**Comment by OmidGhotbi** [comment] 2021-01-21 00:07
For skylight you need to add a little bit of gain, for example, 2.2 gain multiplayer would be a good number for clear sky, Also use a proper exposer for it like auto linear plus gamma correction 2.2 with 512 samples.

**Comment by OmidGhotbi** [comment] 2021-02-17 08:21
Not an issue just an option.

**Closed as completed** 2021-03-14 23:36 UTC
Labels: bug
